{% set name = "polyleven" %}
{% set version = "0.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/polyleven-{{ version }}.tar.gz
  sha256: 73099c4d93d1a55ce9f2017e941ae4dd1528e853140c090dd6233d078ebe75c8

build:
  number: 2
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - polyleven
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://ceptord.net/20181215-polyleven.html
  summary: A fast C-implemented library for Levenshtein distance
  license: SAX-PD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
