{% set name = "polyleven" %}
{% set version = "0.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/polyleven-{{ version }}.tar.gz
  sha256: 2307bd46746ee6e4d56ab2673d5bb4bdb88d3c77b954dd86f03d1363085f4c6d

build:
  number: 1
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - polyleven
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://ceptord.net/20181215-polyleven.html
  summary: A fast C-implemented library for Levenshtein distance
  license: SAX-PD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
