{% set name = "polyleven" %}
{% set version = "0.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/polyleven-{{ version }}.tar.gz
  sha256: 299a93766761b5e5fb4092388f3dc6401224fd436c05f11c4ee48b262587e8da

build:
  number: 0
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - polyleven
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://ceptord.net/20181215-polyleven.html
  summary: A fast C-implemented library for Levenshtein distance
  license: SAX-PD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
